-- Neon bootstrap for the Zarya project
-- Run this file as a whole in Neon SQL Editor.
-- It creates the schema, loads public site content, and inserts admin users.

BEGIN;

CREATE TABLE IF NOT EXISTS admin_user (
    admin_user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    password_hash text NOT NULL,
    full_name varchar(150) NOT NULL,
    role varchar(30) NOT NULL DEFAULT 'manager',
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_admin_user_email UNIQUE (email),
    CONSTRAINT chk_admin_user_role CHECK (role IN ('super_admin', 'editor', 'manager'))
);

CREATE TABLE IF NOT EXISTS product_category (
    product_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL,
    slug varchar(50) NOT NULL,
    sort_order integer NOT NULL DEFAULT 100,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_category_name UNIQUE (name),
    CONSTRAINT uq_product_category_slug UNIQUE (slug),
    CONSTRAINT chk_product_category_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_product_category_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE TABLE IF NOT EXISTS product (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id integer NOT NULL,
    name varchar(180) NOT NULL,
    slug varchar(120) NOT NULL,
    short_description text NOT NULL,
    image_url varchar(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 100,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_slug UNIQUE (slug),
    CONSTRAINT chk_product_price CHECK (price >= 0),
    CONSTRAINT chk_product_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_product_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT fk_product_category FOREIGN KEY (product_category_id)
        REFERENCES product_category (product_category_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS product_specs (
    product_spec_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL,
    label varchar(120) NOT NULL,
    value varchar(120) NOT NULL,
    sort_order integer NOT NULL DEFAULT 100,
    CONSTRAINT chk_product_specs_sort_order CHECK (sort_order >= 0),
    CONSTRAINT fk_product_specs_product FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS news (
    news_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(220) NOT NULL,
    slug varchar(120) NOT NULL,
    preview_text text NOT NULL,
    content text NOT NULL,
    image_url varchar(255) NOT NULL,
    published_at date NOT NULL,
    is_published boolean NOT NULL DEFAULT true,
    created_by_admin_user_id integer NULL,
    updated_by_admin_user_id integer NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_news_slug UNIQUE (slug),
    CONSTRAINT chk_news_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT fk_news_created_by_admin_user FOREIGN KEY (created_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,
    CONSTRAINT fk_news_updated_by_admin_user FOREIGN KEY (updated_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS contact_message (
    contact_message_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_page varchar(20) NOT NULL,
    name varchar(120) NULL,
    phone varchar(32) NULL,
    email varchar(255) NULL,
    message text NULL,
    status varchar(20) NOT NULL DEFAULT 'new',
    created_at timestamptz NOT NULL DEFAULT now(),
    processed_by_admin_user_id integer NULL,
    CONSTRAINT chk_contact_message_source_page CHECK (source_page IN ('home', 'contacts')),
    CONSTRAINT chk_contact_message_status CHECK (status IN ('new', 'in_progress', 'closed', 'spam')),
    CONSTRAINT fk_contact_message_processed_by_admin_user FOREIGN KEY (processed_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS company_contact (
    company_contact_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(150) NOT NULL,
    email varchar(255) NOT NULL,
    job_title varchar(120) NOT NULL,
    phone varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_partner (
    company_partner_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name varchar(255) NOT NULL,
    inn varchar(12) NOT NULL,
    ogrn varchar(15) NOT NULL,
    legal_address text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_company_partner_inn CHECK (inn ~ '^[0-9]{10}$'),
    CONSTRAINT chk_company_partner_ogrn CHECK (ogrn ~ '^[0-9]{13}$')
);

CREATE SEQUENCE IF NOT EXISTS purchase_request_number_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS purchase_request (
    purchase_request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_contact_id integer NOT NULL,
    company_partner_id integer NOT NULL,
    request_number varchar(30) NOT NULL DEFAULT ('ZR-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('purchase_request_number_seq')::text, 6, '0')),
    status varchar(20) NOT NULL DEFAULT 'new',
    agreement_accepted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    processed_by_admin_user_id integer NULL,
    CONSTRAINT uq_purchase_request_request_number UNIQUE (request_number),
    CONSTRAINT chk_purchase_request_status CHECK (status IN ('new', 'in_review', 'quoted', 'approved', 'rejected', 'completed')),
    CONSTRAINT fk_purchase_request_company_contact FOREIGN KEY (company_contact_id)
        REFERENCES company_contact (company_contact_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_request_company_partner FOREIGN KEY (company_partner_id)
        REFERENCES company_partner (company_partner_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_request_processed_by_admin_user FOREIGN KEY (processed_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS request_product (
    request_product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity_tons numeric(10,3) NOT NULL,
    price numeric(12,2) NOT NULL,
    CONSTRAINT chk_request_product_price CHECK (price >= 0),
    CONSTRAINT chk_request_product_quantity_tons CHECK (quantity_tons >= 25),
    CONSTRAINT fk_request_product_purchase_request FOREIGN KEY (purchase_request_id)
        REFERENCES purchase_request (purchase_request_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_request_product_product FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS delivery (
    delivery_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id integer NOT NULL,
    delivery_type varchar(30) NULL,
    delivery_address text NULL,
    delivery_comment text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_delivery_purchase_request_id UNIQUE (purchase_request_id),
    CONSTRAINT chk_delivery_type CHECK (delivery_type IS NULL OR delivery_type IN ('pickup', 'company_transport')),
    CONSTRAINT fk_delivery_purchase_request FOREIGN KEY (purchase_request_id)
        REFERENCES purchase_request (purchase_request_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_product_category_updated_at ON product_category;
CREATE TRIGGER trg_product_category_updated_at
BEFORE UPDATE ON product_category
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_product_updated_at ON product;
CREATE TRIGGER trg_product_updated_at
BEFORE UPDATE ON product
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_news_updated_at ON news;
CREATE TRIGGER trg_news_updated_at
BEFORE UPDATE ON news
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_company_contact_updated_at ON company_contact;
CREATE TRIGGER trg_company_contact_updated_at
BEFORE UPDATE ON company_contact
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_company_partner_updated_at ON company_partner;
CREATE TRIGGER trg_company_partner_updated_at
BEFORE UPDATE ON company_partner
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_purchase_request_updated_at ON purchase_request;
CREATE TRIGGER trg_purchase_request_updated_at
BEFORE UPDATE ON purchase_request
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_delivery_updated_at ON delivery;
CREATE TRIGGER trg_delivery_updated_at
BEFORE UPDATE ON delivery
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_product_product_category_id ON product (product_category_id);
CREATE INDEX IF NOT EXISTS idx_product_specs_product_id ON product_specs (product_id);
CREATE INDEX IF NOT EXISTS idx_news_published_at ON news (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_is_published ON news (is_published);
CREATE INDEX IF NOT EXISTS idx_contact_message_status_created_at ON contact_message (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_request_company_contact_id ON purchase_request (company_contact_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_company_partner_id ON purchase_request (company_partner_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_status_created_at ON purchase_request (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_request_product_purchase_request_id ON request_product (purchase_request_id);
CREATE INDEX IF NOT EXISTS idx_request_product_product_id ON request_product (product_id);

-- Seed only the tables that correspond to public site content.
-- Request-related tables remain empty and should be filled by real submissions.

INSERT INTO product_category (name, slug, sort_order, is_active)
VALUES
    ('Пшеница', 'wheat', 10, true),
    ('Кукуруза', 'corn', 20, true),
    ('Подсолнечник', 'sunflower', 30, true)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active;

INSERT INTO product (product_category_id, name, slug, short_description, image_url, price, is_active, sort_order)
VALUES
    ((SELECT product_category_id FROM product_category WHERE slug = 'wheat'), 'Пшеница озимая Жаворонок', 'wheat-javoronok', 'Продовольственная пшеница. Зерно полновесное, чистое, с хорошей натурой.', 'img/wheat1.jpg', 15100.00, true, 10),
    ((SELECT product_category_id FROM product_category WHERE slug = 'wheat'), 'Пшеница яровая мягкая', 'wheat-soft', 'Чистое продовольственное зерно яровой пшеницы. Содержание клейковины среднее, зерно выполненное.', 'img/wheat2.jpg', 14800.00, true, 20),
    ((SELECT product_category_id FROM product_category WHERE slug = 'wheat'), 'Пшеница яровая твердая Таганрог', 'wheat-taganrog', 'Зерно твердых сортов пшеницы светлого цвета. Богато белком и каротиноидами.', 'img/wheat3.jpg', 15600.00, true, 30),
    ((SELECT product_category_id FROM product_category WHERE slug = 'sunflower'), 'Подсолнечник ЕС Ароматик', 'sunflower-aromatik', 'Крупная, выполненная семечка с высокой масличностью до 52%. Зерно чистое, сухое.', 'img/sunflower1.jpg', 36200.00, true, 40),
    ((SELECT product_category_id FROM product_category WHERE slug = 'sunflower'), 'Подсолнечник Кречет', 'sunflower-krechet', 'Надежный сорт для маслоэкстракции. Масличность стабильно держится в пределах 48–52%, семечка крупная.', 'img/sunflower2.jpg', 35600.00, true, 50),
    ((SELECT product_category_id FROM product_category WHERE slug = 'sunflower'), 'Подсолнечник гибрид Валентина', 'sunflower-valentina', 'Семечка с повышенным содержанием олеиновой кислоты, масло высококачественное, неокисляемое.', 'img/sunflower3.jpg', 35100.00, true, 60),
    ((SELECT product_category_id FROM product_category WHERE slug = 'sunflower'), 'Подсолнечник Барле', 'sunflower-barle', 'Урожайный подсолнечник с масличностью 49–51%. Семечка крупная, качество зерна стабильное.', 'img/sunflower4.jpg', 34700.00, true, 70),
    ((SELECT product_category_id FROM product_category WHERE slug = 'sunflower'), 'Подсолнечник Мас 920 КП', 'sunflower-mas920', 'Среднеспелый гибрид французской селекции. Масличность семян 42,5–47,5%, семечка выровненная.', 'img/sunflower5.jpg', 34100.00, true, 80),
    ((SELECT product_category_id FROM product_category WHERE slug = 'corn'), 'Кукуруза ДКС 4014', 'corn-dks4014', 'Зерно зубовидного типа, желтое, полновесное. Подходит для кормовых целей и переработки на крупу.', 'img/corn1.jpg', 14600.00, true, 90),
    ((SELECT product_category_id FROM product_category WHERE slug = 'corn'), 'Кукуруза ДКС 4178', 'corn-dks4178', 'Зерно зубовидное, желтое, крупное. Гибрид зернового направления, востребован комбикормовыми заводами.', 'img/corn2.jpg', 14900.00, true, 100),
    ((SELECT product_category_id FROM product_category WHERE slug = 'corn'), 'Кукуруза ДКС 3710', 'corn-dks3710', 'Зерно зубовидное, желтое. Гибрид отличается универсальностью, подходит на корм и на переработку.', 'img/corn3.jpg', 14400.00, true, 110)
ON CONFLICT (slug) DO UPDATE SET
    product_category_id = EXCLUDED.product_category_id,
    name = EXCLUDED.name,
    short_description = EXCLUDED.short_description,
    image_url = EXCLUDED.image_url,
    price = EXCLUDED.price,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order;

DELETE FROM product_specs
WHERE product_id IN (
    SELECT product_id
    FROM product
    WHERE slug IN (
        'wheat-javoronok',
        'wheat-soft',
        'wheat-taganrog',
        'sunflower-aromatik',
        'sunflower-krechet',
        'sunflower-valentina',
        'sunflower-barle',
        'sunflower-mas920',
        'corn-dks4014',
        'corn-dks4178',
        'corn-dks3710'
    )
);

INSERT INTO product_specs (product_id, label, value, sort_order)
VALUES
    ((SELECT product_id FROM product WHERE slug = 'wheat-javoronok'), 'Содержание клейковины', '28–30%', 10),
    ((SELECT product_id FROM product WHERE slug = 'wheat-javoronok'), 'Качество клейковины', '70–80 ед.', 20),
    ((SELECT product_id FROM product WHERE slug = 'wheat-javoronok'), 'Натура зерна', '780–810 г/л', 30),
    ((SELECT product_id FROM product WHERE slug = 'wheat-javoronok'), 'Влажность', 'не более 14%', 40),
    ((SELECT product_id FROM product WHERE slug = 'wheat-soft'), 'Содержание клейковины', '24–27%', 10),
    ((SELECT product_id FROM product WHERE slug = 'wheat-soft'), 'Качество клейковины', '65–75 ед.', 20),
    ((SELECT product_id FROM product WHERE slug = 'wheat-soft'), 'Натура зерна', '760–790 г/л', 30),
    ((SELECT product_id FROM product WHERE slug = 'wheat-soft'), 'Влажность', 'до 14%', 40),
    ((SELECT product_id FROM product WHERE slug = 'wheat-taganrog'), 'Содержание клейковины', '26–28%', 10),
    ((SELECT product_id FROM product WHERE slug = 'wheat-taganrog'), 'Качество клейковины', '55–70 ед.', 20),
    ((SELECT product_id FROM product WHERE slug = 'wheat-taganrog'), 'Натура зерна', '770–800 г/л', 30),
    ((SELECT product_id FROM product WHERE slug = 'wheat-taganrog'), 'Влажность', 'до 14%', 40),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-aromatik'), 'Масличность', 'до 52%', 10),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-aromatik'), 'Масса 1000 семян', '65–72 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-aromatik'), 'Влажность', 'до 8%', 30),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-aromatik'), 'Сорная примесь', 'до 2%', 40),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-krechet'), 'Масличность', '48–52%', 10),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-krechet'), 'Масса 1000 семян', '62–68 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-krechet'), 'Влажность', 'до 8%', 30),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-krechet'), 'Сорная примесь', 'до 2%', 40),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-valentina'), 'Масличность', 'до 50%', 10),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-valentina'), 'Масса 1000 семян', '58–64 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-valentina'), 'Влажность', 'до 8%', 30),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-valentina'), 'Сорная примесь', 'до 2%', 40),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-barle'), 'Масличность', '49–51%', 10),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-barle'), 'Масса 1000 семян', '65–72 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-barle'), 'Влажность', 'до 8%', 30),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-barle'), 'Сорная примесь', 'до 2%', 40),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-mas920'), 'Масличность', '42,5–47,5%', 10),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-mas920'), 'Масса 1000 семян', '58–63 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-mas920'), 'Влажность', 'до 8%', 30),
    ((SELECT product_id FROM product WHERE slug = 'sunflower-mas920'), 'Сорная примесь', 'до 2%', 40),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4014'), 'Тип зерна', 'зубовидный', 10),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4014'), 'Масса 1000 зёрен', '280–320 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4014'), 'Влажность', 'до 14%', 30),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4014'), 'Содержание крахмала', '68–70%', 40),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4178'), 'Тип зерна', 'зубовидный', 10),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4178'), 'Масса 1000 зёрен', '320–340 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4178'), 'Влажность', 'до 14%', 30),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks4178'), 'Содержание крахмала', '70–72%', 40),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks3710'), 'Тип зерна', 'зубовидный', 10),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks3710'), 'Масса 1000 зёрен', '300–330 г', 20),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks3710'), 'Влажность', 'до 14%', 30),
    ((SELECT product_id FROM product WHERE slug = 'corn-dks3710'), 'Содержание крахмала', '69–71%', 40);

INSERT INTO news (title, slug, preview_text, content, image_url, published_at, is_published)
VALUES
    (
        'Завершена постройка зернокомплекса',
        'grain-complex',
        'Успешно закончена постройка зерноперерабатывающего комплекса в сотрудничестве с «АгроТехника»...',
        'Успешно закончена постройка зерноперерабатывающего комплекса в сотрудничестве с «АгроТехника». ООО «Заря» (г. Жирновск, Волгоградская область) ввело в эксплуатацию новый объект для приема, очистки, сушки и хранения зерновых и масличных культур. Проектные и строительно-монтажные работы выполнены компанией «АгроТехника».

Объект предназначен для послеуборочной обработки пшеницы, кукурузы и подсолнечника, выращиваемых предприятием на территории Жирновского района. Производственная мощность зерносушильного оборудования составляет 18 тонн в час на кукурузе. В состав комплекса входят крытый зерносклад ангарного типа на 3200 тонн хранения, приемный бункер с механизированной завальной ямой, сепаратор первичной очистки и система транспортных конвейеров.

Генеральный директор ООО «Заря» Ключкин Олег Анатольевич сообщил, что пусконаладочные работы завершены в плановые сроки. По состоянию на текущую дату комплекс готов к приему зерна нового урожая. Выход на проектную мощность запланирован на период уборочной кампании текущего сельскохозяйственного года. Строительство объекта позволяет предприятию осуществлять полный цикл подработки урожая на собственной базе без привлечения мощностей сторонних элеваторов. Дополнительно на комплексе организовано 6 рабочих мест для обслуживающего персонала.',
        'img/news1.jpg',
        DATE '2025-05-02',
        true
    ),
    (
        'Посевная кампания',
        'sowing-campaign',
        'Завершен комплекс весенних полевых работ по засеванию семян пшена и кукурузы...',
        'Завершен комплекс весенних полевых работ по засеванию сельскохозяйственных культур на территории Жирновского района Волгоградской области. В рамках посевной кампании были полностью засеяны площади, отведенные под пшено и кукурузу, с применением современной техники и высококачественного посевного материала.

Общая площадь посевов составила более 620 гектаров. Работы проводились в оптимальные агротехнические сроки с учетом погодных условий региона. Для повышения всхожести и дальнейшей устойчивости растений применялись минеральные удобрения и средства защиты растений, подобранные с учетом характеристик почвы.

По словам руководства предприятия, посевная кампания прошла в штатном режиме, без сбоев и отклонений от утвержденного графика. В настоящее время специалисты осуществляют контроль за состоянием всходов, а также проводят плановые агротехнические мероприятия, направленные на обеспечение стабильного роста культур.

Отдельное внимание в ходе кампании было уделено равномерности заделки семян и сохранению оптимального уровня влажности на участках. Это позволяет рассчитывать на устойчивое развитие посевов и формирование стабильной урожайности в рамках текущего сельскохозяйственного сезона.',
        'img/news2.jpg',
        DATE '2025-03-10',
        true
    ),
    (
        'Новые оросители',
        'new-irrigators',
        'Покупка позволит повысить урожайность и снизить зависимость от погодных условий...',
        'В рамках программы модернизации сельскохозяйственного производства завершено внедрение нового оросительного оборудования. Приобретенные системы направлены на повышение урожайности и снижение зависимости от погодных условий в период активного роста культур.

На полях установлены современные дождевальные установки, обеспечивающие равномерное распределение влаги и оптимальный режим орошения. Новая система охватывает более 300 гектаров посевных площадей, что позволяет существенно повысить эффективность использования сельскохозяйственных угодий.

Использование оросительных установок особенно актуально в условиях засушливого климата региона. По оценке специалистов, внедрение данного оборудования позволит не только стабилизировать урожайность, но и повысить качество выращиваемой продукции. В настоящее время система полностью введена в эксплуатацию и готова к работе в течение всего вегетационного периода.

Дополнительно была проведена настройка режимов полива для разных типов культур, что позволит точнее расходовать водные ресурсы и поддерживать поля в оптимальном агротехническом состоянии в периоды повышенной температуры.',
        'img/news3.jpg',
        DATE '2025-02-20',
        true
    ),
    (
        'Новые силосы для зерна',
        'new-silos',
        'Завершены работы по установке новых силосов. Общая вместимость зернохранилищ значительно выросла...',
        'Завершены работы по установке новых силосов для хранения зерновых культур на территории производственной базы. В результате модернизации значительно увеличены мощности по хранению урожая.

Общая вместимость зернохранилищ выросла более чем на 5 000 тонн. Новые силосы оснащены современными системами вентиляции, контроля температуры и влажности, что позволяет обеспечить оптимальные условия хранения продукции в течение длительного времени.

Расширение инфраструктуры хранения дает возможность гибко управлять объемами отгрузки и снижает зависимость от сторонних складских мощностей. По оценке специалистов, это также положительно скажется на сохранении качества зерна и общей эффективности работы предприятия.

Новая линия хранения уже интегрирована в существующую производственную схему, что позволяет быстрее перераспределять партии зерна и поддерживать стабильную загрузку складских мощностей в период активного поступления урожая.',
        'img/news7.jpg',
        DATE '2024-09-07',
        true
    ),
    (
        'Отгрузка зерна партнеру',
        'partner-shipment',
        'Осуществлена отгрузка первой партии пшеницы объемом 1 200 тонн в адрес компании «ЗерноТрейд»...',
        'Осуществлена отгрузка первой партии пшеницы объемом 1 200 тонн в адрес компании «ЗерноТрейд» в рамках действующего договора поставки. Поставка стала частью плановой реализации продукции нового урожая.

Перед отгрузкой зерно прошло полный цикл послеуборочной обработки, включая очистку и подготовку на собственных производственных мощностях. Это позволило обеспечить соответствие продукции установленным требованиям и стандартам качества.

Отгрузка была выполнена в установленные сроки с соблюдением всех логистических и технологических процедур. Представители предприятия отмечают, что сотрудничество с партнерами развивается стабильно и имеет перспективы дальнейшего расширения. В ближайшее время планируется формирование и отправка следующих партий зерновых культур.

Для обеспечения бесперебойной логистики была заранее подготовлена инфраструктура погрузки и оформлен полный комплект сопроводительной документации. Это позволило провести отправку без задержек и сохранить темп выполнения договорных обязательств.',
        'img/news4.jpg',
        DATE '2024-09-07',
        true
    ),
    (
        'Ремонт дороги к дальним полям',
        'road-repair',
        'В летний период выполнены работы по ремонту полевых дорог, ведущих к удаленным участкам...',
        'В летний период выполнены работы по ремонту полевых дорог, ведущих к удаленным сельскохозяйственным участкам. Основной задачей стало улучшение транспортной доступности и обеспечение бесперебойного движения техники.

В ходе ремонта наиболее проблемные участки были выровнены и засыпаны щебнем. Общая протяженность восстановленных дорог составила более 8 километров. Проведенные мероприятия позволили значительно повысить проходимость даже в неблагоприятных погодных условиях.

Обновление дорожной инфраструктуры особенно важно в период активных полевых работ и уборочной кампании. По мнению специалистов, это позволит сократить временные затраты и снизить нагрузку на технику.

Благодаря проведенному ремонту техника получила более устойчивый и безопасный доступ к удаленным участкам, что особенно важно при перевозке урожая и организации бесперебойной работы в условиях интенсивного сезона.',
        'img/news8.jpg',
        DATE '2024-08-23',
        true
    ),
    (
        'Уборка озимой пшеницы',
        'winter-wheat-harvest',
        'Завершена уборка озимой пшеницы, посевы которой занимали площадь 410 гектаров. Средняя урожайность составила...',
        'Завершена уборка озимой пшеницы, посевы которой занимали площадь 410 гектаров. Уборочная кампания была проведена в оптимальные сроки с использованием современной высокопроизводительной техники, что позволило минимизировать потери урожая.

Средняя урожайность составила 42 центнера с гектара, что соответствует плановым показателям и подтверждает эффективность применяемых агротехнических решений. Полученное зерно отличается высоким качеством и направлено на дальнейшую обработку и хранение.

По итогам кампании специалисты отмечают стабильные производственные результаты и благоприятное влияние погодных условий в ключевые периоды роста культуры. В настоящее время предприятие приступает к уборке других сельскохозяйственных культур, входящих в производственный цикл.

Зерно нового урожая уже поступает на собственные мощности для очистки и подготовки к хранению. Это позволяет сохранить качество партии и обеспечить дальнейшую отгрузку в соответствии с производственным и коммерческим графиком предприятия.',
        'img/news5.jpg',
        DATE '2024-08-23',
        true
    ),
    (
        'Крупная железнодорожная отгрузка',
        'rail-shipment',
        'Проведена крупная отгрузка кукурузы объемом 2 500 тонн в адрес международной компании «Каргилл»...',
        'Проведена крупная отгрузка кукурузы объемом 2 500 тонн в адрес международной компании «Каргилл». Поставка осуществлялась железнодорожным транспортом через региональный логистический узел.

Для выполнения отгрузки было задействовано более 40 специализированных вагонов-зерновозов. Погрузка осуществлялась с использованием механизированных систем, что позволило обеспечить высокую скорость обработки и соблюдение графика поставки.

Реализация подобных объемов продукции свидетельствует о стабильной работе предприятия и высоком уровне организации логистических процессов. Сотрудничество с крупными партнерами подтверждает соответствие продукции международным стандартам качества.

В компании отмечают, что подобные поставки требуют точной координации работы склада, транспортных служб и отдела контроля качества. Полученный опыт будет использован при подготовке следующих крупных логистических партий.',
        'img/news6.jpg',
        DATE '2024-04-15',
        true
    ),
    (
        'Обновление парка техники',
        'fleet-update',
        'Продолжается планомерное обновление парка сельскохозяйственной техники. Приобретен новый трактор...',
        'Продолжается планомерное обновление парка сельскохозяйственной техники. В рамках текущего этапа была приобретена новая единица — высокопроизводительный трактор, оснащенный современным навесным оборудованием.

Техника предназначена для выполнения широкого спектра задач, включая обработку почвы, посев и другие агротехнические операции. Использование современных машин позволяет повысить точность работ и снизить расход ресурсов.

По словам руководства, обновление техники является важной частью стратегии развития предприятия. В дальнейшем планируется продолжение модернизации, направленной на повышение производительности и эффективности сельскохозяйственных процессов.

Новая техника уже введена в рабочий цикл и используется на ключевых этапах сезонных операций. Это позволяет повысить темп выполнения задач и улучшить качество обработки полей без лишней нагрузки на действующий парк машин.',
        'img/news9.jpg',
        DATE '2024-03-29',
        true
    ),
    (
        'Страхование урожая',
        'crop-insurance',
        'Заключен договор страхования урожая на предстоящий сельскохозяйственный год с одной из ведущих компаний...',
        'Заключен договор страхования урожая на предстоящий сельскохозяйственный год с одной из ведущих страховых компаний региона. Страховое покрытие распространяется на основные выращиваемые культуры.

Документ предусматривает защиту от широкого спектра рисков, включая неблагоприятные погодные условия, такие как засуха, град и резкие перепады температур. Общая площадь застрахованных посевов превышает 700 гектаров.

Применение страховых механизмов позволяет снизить финансовые риски и обеспечить стабильность хозяйственной деятельности. По мнению специалистов, это важный элемент современной системы управления сельскохозяйственным производством.

Оформление страховой защиты позволяет предприятию увереннее планировать производственный сезон и поддерживать устойчивость работы даже при возможных неблагоприятных сценариях развития погодной ситуации.',
        'img/news10.jpg',
        DATE '2023-11-18',
        true
    )
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    preview_text = EXCLUDED.preview_text,
    content = EXCLUDED.content,
    image_url = EXCLUDED.image_url,
    published_at = EXCLUDED.published_at,
    is_published = EXCLUDED.is_published,
    updated_at = now();

INSERT INTO admin_user (email, password_hash, full_name, role, is_active)
VALUES
    ('admin@zarya.local', '$2b$10$D4i4ZeUAO9w3LqPkhUGhYONxuMkFgLIuEY516q94yZtbl0MrvLvgS', 'Администратор', 'super_admin', true)
ON CONFLICT (email) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    is_active = EXCLUDED.is_active;

DELETE FROM admin_user
WHERE email IN ('editor@zarya.local', 'manager@zarya.local');

COMMIT;
