BEGIN;

CREATE TABLE IF NOT EXISTS admin_user (
    admin_user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    password_hash text NOT NULL,
    full_name varchar(150) NOT NULL,
    role varchar(30) NOT NULL DEFAULT 'manager',
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_admin_user_email UNIQUE (email),
    CONSTRAINT chk_admin_user_role CHECK (role IN ('super_admin', 'editor', 'manager'))
);

CREATE TABLE IF NOT EXISTS product_category (
    product_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL,
    slug varchar(50) NOT NULL,
    sort_order integer NOT NULL DEFAULT 100,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_category_name UNIQUE (name),
    CONSTRAINT uq_product_category_slug UNIQUE (slug),
    CONSTRAINT chk_product_category_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_product_category_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE TABLE IF NOT EXISTS product (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id integer NOT NULL,
    name varchar(180) NOT NULL,
    slug varchar(120) NOT NULL,
    short_description text NOT NULL,
    image_url varchar(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 100,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_slug UNIQUE (slug),
    CONSTRAINT chk_product_price CHECK (price >= 0),
    CONSTRAINT chk_product_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_product_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT fk_product_category FOREIGN KEY (product_category_id)
        REFERENCES product_category (product_category_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS product_specs (
    product_spec_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL,
    label varchar(120) NOT NULL,
    value varchar(120) NOT NULL,
    sort_order integer NOT NULL DEFAULT 100,
    CONSTRAINT chk_product_specs_sort_order CHECK (sort_order >= 0),
    CONSTRAINT fk_product_specs_product FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS news (
    news_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(220) NOT NULL,
    slug varchar(120) NOT NULL,
    preview_text text NOT NULL,
    content text NOT NULL,
    image_url varchar(255) NOT NULL,
    published_at date NOT NULL,
    is_published boolean NOT NULL DEFAULT true,
    created_by_admin_user_id integer NULL,
    updated_by_admin_user_id integer NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_news_slug UNIQUE (slug),
    CONSTRAINT chk_news_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT fk_news_created_by_admin_user FOREIGN KEY (created_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,
    CONSTRAINT fk_news_updated_by_admin_user FOREIGN KEY (updated_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS contact_message (
    contact_message_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_page varchar(20) NOT NULL,
    name varchar(120) NULL,
    phone varchar(32) NULL,
    email varchar(255) NULL,
    message text NULL,
    status varchar(20) NOT NULL DEFAULT 'new',
    created_at timestamptz NOT NULL DEFAULT now(),
    processed_by_admin_user_id integer NULL,
    CONSTRAINT chk_contact_message_source_page CHECK (source_page IN ('home', 'contacts')),
    CONSTRAINT chk_contact_message_status CHECK (status IN ('new', 'in_progress', 'closed', 'spam')),
    CONSTRAINT fk_contact_message_processed_by_admin_user FOREIGN KEY (processed_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS company_contact (
    company_contact_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(150) NOT NULL,
    email varchar(255) NOT NULL,
    job_title varchar(120) NOT NULL,
    phone varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_partner (
    company_partner_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name varchar(255) NOT NULL,
    inn varchar(12) NOT NULL,
    ogrn varchar(15) NOT NULL,
    legal_address text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_company_partner_inn CHECK (inn ~ '^[0-9]{10}$'),
    CONSTRAINT chk_company_partner_ogrn CHECK (ogrn ~ '^[0-9]{13}$')
);

CREATE SEQUENCE IF NOT EXISTS purchase_request_number_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS purchase_request (
    purchase_request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_contact_id integer NOT NULL,
    company_partner_id integer NOT NULL,
    request_number varchar(30) NOT NULL DEFAULT ('ZR-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('purchase_request_number_seq')::text, 6, '0')),
    status varchar(20) NOT NULL DEFAULT 'new',
    agreement_accepted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    processed_by_admin_user_id integer NULL,
    CONSTRAINT uq_purchase_request_request_number UNIQUE (request_number),
    CONSTRAINT chk_purchase_request_status CHECK (status IN ('new', 'in_review', 'quoted', 'approved', 'rejected', 'completed')),
    CONSTRAINT fk_purchase_request_company_contact FOREIGN KEY (company_contact_id)
        REFERENCES company_contact (company_contact_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_request_company_partner FOREIGN KEY (company_partner_id)
        REFERENCES company_partner (company_partner_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_request_processed_by_admin_user FOREIGN KEY (processed_by_admin_user_id)
        REFERENCES admin_user (admin_user_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS request_product (
    request_product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity_tons numeric(10,3) NOT NULL,
    price numeric(12,2) NOT NULL,
    CONSTRAINT chk_request_product_price CHECK (price >= 0),
    CONSTRAINT chk_request_product_quantity_tons CHECK (quantity_tons >= 25),
    CONSTRAINT fk_request_product_purchase_request FOREIGN KEY (purchase_request_id)
        REFERENCES purchase_request (purchase_request_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_request_product_product FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS delivery (
    delivery_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id integer NOT NULL,
    delivery_type varchar(30) NULL,
    delivery_address text NULL,
    delivery_comment text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_delivery_purchase_request_id UNIQUE (purchase_request_id),
    CONSTRAINT chk_delivery_type CHECK (delivery_type IS NULL OR delivery_type IN ('pickup', 'company_transport')),
    CONSTRAINT fk_delivery_purchase_request FOREIGN KEY (purchase_request_id)
        REFERENCES purchase_request (purchase_request_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_product_category_updated_at ON product_category;
CREATE TRIGGER trg_product_category_updated_at
BEFORE UPDATE ON product_category
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_product_updated_at ON product;
CREATE TRIGGER trg_product_updated_at
BEFORE UPDATE ON product
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_news_updated_at ON news;
CREATE TRIGGER trg_news_updated_at
BEFORE UPDATE ON news
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_company_contact_updated_at ON company_contact;
CREATE TRIGGER trg_company_contact_updated_at
BEFORE UPDATE ON company_contact
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_company_partner_updated_at ON company_partner;
CREATE TRIGGER trg_company_partner_updated_at
BEFORE UPDATE ON company_partner
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_purchase_request_updated_at ON purchase_request;
CREATE TRIGGER trg_purchase_request_updated_at
BEFORE UPDATE ON purchase_request
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_delivery_updated_at ON delivery;
CREATE TRIGGER trg_delivery_updated_at
BEFORE UPDATE ON delivery
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_product_product_category_id ON product (product_category_id);
CREATE INDEX IF NOT EXISTS idx_product_specs_product_id ON product_specs (product_id);
CREATE INDEX IF NOT EXISTS idx_news_published_at ON news (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_is_published ON news (is_published);
CREATE INDEX IF NOT EXISTS idx_contact_message_status_created_at ON contact_message (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_request_company_contact_id ON purchase_request (company_contact_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_company_partner_id ON purchase_request (company_partner_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_status_created_at ON purchase_request (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_request_product_purchase_request_id ON request_product (purchase_request_id);
CREATE INDEX IF NOT EXISTS idx_request_product_product_id ON request_product (product_id);

COMMIT;